### ISSUE TITLE
Question about running docker inside docker and report result properly to jenkins dind instance

### ISSUE THREAD

**Issue by ialex** [killercentury/docker-jenkins-dind#1]
Im using docker-compose to setup my app containers and then run the tests but they do not properly report to jenkins when a tests fail do you know how to accomplish this??

im using python and unittest runner im running tests like this:

docker-compose up -d 
docker exec -i workspace_wadev_1 python run_tests.py

Thanks in advance for your support

**Comment by killercentury** [comment]
I guess you maybe better to check the exit code from your tests in the container. I personally run a few different testing frameworks, such as Cucumber, Protractor, Behave and so on, but none of them has issue.

**Comment by ialex** [comment]
Yes it seems that it is behaving properly, thanks
